## Logistic Regression & RandomSearch 

In [2]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt
import seaborn as sns 

from sklearn.datasets import make_classification

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score , classification_report , confusion_matrix


In [9]:
x ,y =make_classification(n_samples= 2000 , 
                    n_features= 50 , 
                    n_informative= 10 , 
                    random_state= 812 ,
                    n_classes= 2)
x

array([[ 1.23173717,  1.10532801,  0.22776564, ..., -0.78356596,
        -0.15711703, -1.65414508],
       [ 0.48439638, -0.14303632, -2.51423517, ...,  0.60566089,
        -0.13130922, -0.21336398],
       [ 1.43086386, -0.13222191, -0.97300061, ..., -1.24373168,
        -0.8441854 , -1.68326389],
       ...,
       [ 1.31133403,  0.03317187,  2.49820238, ..., -0.42860444,
         1.11198425, -0.37050314],
       [ 1.40062972, -0.98004073, -0.89407227, ...,  1.63212064,
         0.06716772,  1.21445157],
       [ 0.44062982, -0.17520526,  3.96299506, ...,  0.25240773,
        -0.095253  ,  0.83673848]])

In [10]:
x.shape

(2000, 50)

In [20]:
x_train , x_test , y_train , y_test = train_test_split(x, y, random_state= 42 , test_size= 0.2 )

In [21]:
x_test.shape , x_train.shape

((400, 50), (1600, 50))

In [22]:
vanilla_lr = LogisticRegression()

In [23]:
vanilla_lr.fit(x_train , y_train)

LogisticRegression()

In [27]:
vanilla_pred = vanilla_lr.predict(x_test)
vanilla_pred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,

In [28]:
y_test

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,

In [29]:
accuracy_score(y_test , vanilla_pred)

0.73

In [34]:
print(classification_report(y_test , vanilla_pred , digits=3))

              precision    recall  f1-score   support

           0      0.693     0.759     0.724       187
           1      0.769     0.704     0.735       213

    accuracy                          0.730       400
   macro avg      0.731     0.732     0.730       400
weighted avg      0.733     0.730     0.730       400



In [32]:
confusion_matrix(y_test , vanilla_pred)

array([[142,  45],
       [ 63, 150]], dtype=int64)

## Hyperparameter Tuning

In [35]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
model2 = LogisticRegression()

In [55]:
param_dist = {"C" : [0.01 , 0.1 , 1 , 10 , 100],
              "penalty" : ["l1" , "l2"],
              "solver" : ["saga" , "liblinear"]}

In [56]:
random_search = RandomizedSearchCV(estimator=model2 , param_distributions= param_dist , cv = 5 , n_iter= 5 , verbose = 1 )

In [57]:
random_search.fit(x_train , y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=5,
                   param_distributions={'C': [0.01, 0.1, 1, 10, 100],
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['saga', 'liblinear']},
                   verbose=1)

In [58]:
random_search.best_params_

{'solver': 'liblinear', 'penalty': 'l1', 'C': 1}

In [59]:
best_model = random_search.best_estimator_

In [60]:
tuned_preds = best_model.predict(x_test)

In [61]:
print(classification_report(y_test , tuned_preds , digits=3))

              precision    recall  f1-score   support

           0      0.695     0.754     0.723       187
           1      0.766     0.709     0.737       213

    accuracy                          0.730       400
   macro avg      0.731     0.731     0.730       400
weighted avg      0.733     0.730     0.730       400



In [75]:
tuned_proba = best_model.predict_proba(x_test)[: , 1]
tuned_proba

array([0.93803516, 0.66567702, 0.8320989 , 0.42113836, 0.76028673,
       0.74797943, 0.37352984, 0.93862589, 0.93089539, 0.29051212,
       0.89823331, 0.70306181, 0.6168268 , 0.23544585, 0.91248282,
       0.48942873, 0.32598348, 0.4264076 , 0.95973924, 0.63066565,
       0.27497185, 0.61759325, 0.04415362, 0.74358374, 0.08082753,
       0.32123412, 0.04991091, 0.17759308, 0.96236052, 0.80263808,
       0.2016535 , 0.68076926, 0.22143278, 0.41982554, 0.73082014,
       0.07873106, 0.98307607, 0.63009959, 0.31598294, 0.87206759,
       0.23839818, 0.22867575, 0.69534132, 0.34108422, 0.57720235,
       0.19782888, 0.33507543, 0.99342408, 0.99397272, 0.86250427,
       0.50831792, 0.33994788, 0.21519529, 0.53227511, 0.21930223,
       0.23979916, 0.04204388, 0.22421382, 0.69954239, 0.16186574,
       0.78817204, 0.09190189, 0.40279121, 0.72115361, 0.43026927,
       0.60335855, 0.3461826 , 0.69975376, 0.35005757, 0.0799684 ,
       0.04628742, 0.4467099 , 0.30683581, 0.55292374, 0.09209

In [76]:
np.where(tuned_proba > 0.5 , 1 , 0)

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,